### ISSUE TITLE
Error when parsing from byteString

### ISSUE THREAD

**Issue by Xanawatt** [kszlim/osu-replay-parser#21]
I am getting this error when I try to call replay.parse_replay (replacing "very long string==" with the actual string):

`Traceback (most recent call last):
  File "C:/git/osuHitsoundOverlayer/osu!BeatmapOverlayerV2.py", line 12, in <module>
    print(replay.parse_replay(b"very long string==").number_300s)
  File "C:\git\osuHitsoundOverlayer\venv\lib\site-packages\osrparse\replay.py", line 141, in parse_replay
    return Replay(replay_data)
  File "C:\git\osuHitsoundOverlayer\venv\lib\site-packages\osrparse\replay.py", line 40, in __init__
    self.parse_replay_and_initialize_fields(replay_data)
  File "C:\git\osuHitsoundOverlayer\venv\lib\site-packages\osrparse\replay.py", line 43, in parse_replay_and_initialize_fields
    self.parse_game_mode_and_version(replay_data)
  File "C:\git\osuHitsoundOverlayer\venv\lib\site-packages\osrparse\replay.py", line 56, in parse_game_mode_and_version
    self.game_mode, self.game_version = (GameMode(data[0]), data[1])
  File "C:\Users\schne\AppData\Local\Programs\Python\Python37\lib\enum.py", line 307, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\schne\AppData\Local\Programs\Python\Python37\lib\enum.py", line 555, in __new__
    return cls._missing_(value)
  File "C:\Users\schne\AppData\Local\Programs\Python\Python37\lib\enum.py", line 568, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 88 is not a valid GameMode`

Am I doing something wrong here?

**Comment by kszlim** [comment]
What game mode is this parsing from? Sorry for the ultra late response. If you're still interested, I can re-open this issue.
