### ISSUE TITLE
Lazer replays fail to parse

### ISSUE THREAD

**Issue by NiceAesth** [kszlim/osu-replay-parser#38]
```py
Traceback (most recent call last):
  File "/home/niceaesth/Programming/osu-frame-checker/main.py", line 11, in <module>
    replay = Replay.from_path(f"replays/{replay_path}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niceaesth/.local/share/virtualenvs/osu-frame-checker-A_4Oin16/lib/python3.11/site-packages/osrparse/replay.py", line 368, in from_path
    return Replay.from_file(f)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/niceaesth/.local/share/virtualenvs/osu-frame-checker-A_4Oin16/lib/python3.11/site-packages/osrparse/replay.py", line 386, in from_file
    return Replay.from_string(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niceaesth/.local/share/virtualenvs/osu-frame-checker-A_4Oin16/lib/python3.11/site-packages/osrparse/replay.py", line 403, in from_string
    return _Unpacker(data).unpack()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niceaesth/.local/share/virtualenvs/osu-frame-checker-A_4Oin16/lib/python3.11/site-packages/osrparse/replay.py", line 151, in unpack
    (replay_data, rng_seed) = self.unpack_play_data(mode)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niceaesth/.local/share/virtualenvs/osu-frame-checker-A_4Oin16/lib/python3.11/site-packages/osrparse/replay.py", line 69, in unpack_play_data
    (replay_data, rng_seed) = self.parse_replay_data(data, mode)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niceaesth/.local/share/virtualenvs/osu-frame-checker-A_4Oin16/lib/python3.11/site-packages/osrparse/replay.py", line 85, in parse_replay_data
    keys = int(event[3])
           ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

I would assume that this is due to lazer adding a third key for smoke?

**Comment by tybug** [comment]
please upload the offending osr file

**Comment by NiceAesth** [comment]
[replay.tar.gz](https://github.com/kszlim/osu-replay-parser/files/10202878/replay.tar.gz)

**Comment by tybug** [comment]
I believe this was fixed by https://github.com/kszlim/osu-replay-parser/pull/34. I've released a new version with that fix - please give it a try.

**Comment by NiceAesth** [comment]
seems to work now, thanks!
